#!/bin/bash
clear
releaseOS=$(gawk -F= '/^NAME/{print $2}' /etc/os-release)
releaseArch=$(uname -m)
serverRunning=$(ps cax | grep mta-server)
if [ -d ~/.mtasa ]; then
  if [ $releaseArch == "i686" ]; then
    if [[ $serverRunning == *"mta-server"* ]]; then
      while true; do
        read -p "   MTA:SA Server is already running. Do you want to stop it? [y/n]" yn
        case $yn in
          [Yy]* ) pkill mta-server; echo -e "\033[32m   Server has been stopped.\033[37m"; break;;
          [Nn]* ) exit;;
          * ) echo "Please answer yes or no."
        esac
      done
    else
      echo -e "\033[32m   Server has been started.\033[37m"
      ~/.mtasa/multitheftauto_linux-1.4.1/mta-server >/dev/null 2>&1 &
    fi
  elif [ $releaseArch == "x86_64" ]; then
    if [[ $serverRunning == *"mta-server"* ]]; then
      while true; do
        read -p "   MTA:SA Server is already running. Do you want to stop it? [y/n]" yn
        case $yn in
          [Yy]* ) pkill mta-server; echo -e "\033[32m   Server has been stopped.\033[37m"; break;;
          [Nn]* ) exit;;
          * ) echo "Please answer yes or no."
        esac
      done
    else
      echo -e "\033[32m   Server has been started.\033[37m"
      ~/.mtasa/multitheftauto_linux_x64-1.4.1/mta-server >/dev/null 2>&1 &
    fi
  fi
  exit
fi
echo -e "\033[37m"
echo " ╔═══════════════════════════════════════════════════════╗"
echo " ║ Bart's Linux Tutorials ║ MTA:SA Server Installer      ║"
echo " ╚═══════════════════════════════════════════════════════╝"
echo " ╔═══════════════════════════════════════════════════════╗"
echo -e " ║ ! ║                  Use \033[32m./mtasa \033[37mto start/stop server ║"
echo " ╚═══════════════════════════════════════════════════════╝"
echo " "
echo -e " * Checking if Fedora / CentOS / Debian / Ubuntu.."
if [[ $releaseOS == *"Fedora"* ]]; then
  echo -e "\033[32m   Fedora"
  echo -e "\033[37m"
  osRoot="yum"
elif [[ $releaseOS == *"CentOS"* ]]; then
  echo -e "\033[32m   CentOS"
  echo -e "\033[37m"
  osRoot="yum"
elif [[ $releaseOS == *"Debian"* ]]; then
  echo -e "\033[32m   Debian"
  echo -e "\033[37m"
  osRoot="apt"
elif [[ $releaseOS == *"Ubuntu"* ]]; then
  echo -e "\033[32m   Ubuntu"
  echo -e "\033[37m"
  osRoot="apt"
else
  echo -e "\033[31m   Unsupported :("
  exit
fi

echo -e " * Checking if wget is installed.. "
if [ $osRoot == "yum" ]; then
  yum -y install wget > /dev/null
elif [ $osRoot == "apt" ]; then
  apt-get -y install wget > /dev/null
fi
echo -e "\033[32m   Done!"
echo -e "\033[37m"
echo -e " * Checking if 32bit or 64bit.. "
if [ $releaseArch == "x86_64" ]; then
  echo -e "\033[32m   64bit"
  echo -e "\033[37m"
elif [ $releaseArch == "i686" ]; then
  echo -e "\033[32m   32bit"
  echo -e "\033[37m"
fi
echo -e " * Creating install directory.. "
mkdir ~/.mtasa
echo -e "\033[32m   Done!"
echo -e "\033[37m"
echo -e " * Downloading MTA:SA Server.. "
if [ $releaseArch == "x86_64" ]; then
  cd ~/.mtasa
  wget -q http://linux.mtasa.com/dl/141/multitheftauto_linux_x64-1.4.1.tar.gz
elif [ $releaseArch == "i686" ]; then
  cd ~/.mtasa
  wget -q http://linux.mtasa.com/dl/141/multitheftauto_linux-1.4.1.tar.gz
fi
echo -e "\033[32m   Done!"
echo -e "\033[37m"
echo -e " * Unpacking server files.. "
if [ $releaseArch == "x86_64" ]; then
  cd ~/.mtasa
  tar -xzf multitheftauto_linux_x64-1.4.1.tar.gz
elif [ $releaseArch == "i686" ]; then
  cd ~/.mtasa
  tar -xzf multitheftauto_linux-1.4.1.tar.gz
fi
echo -e "\033[32m   Done!"
echo -e "\033[37m"
echo -e " * Starting server for the first time.. "
if [ $releaseArch == "i686" ]; then
  ~/.mtasa/multitheftauto_linux-1.4.1/mta-server >/dev/null 2>&1 &
elif [ $releaseArch == "x86_64" ]; then
  ~/.mtasa/multitheftauto_linux_x64-1.4.1/mta-server >/dev/null 2>&1 &
fi
